DROP DATABASE IF EXISTS fruitwatchdb;
CREATE DATABASE fruitwatchdb;
USE fruitwatchdb;

CREATE TABLE tblUsers (
	fldID 		 BIGINT AUTO_INCREMENT PRIMARY KEY,
	fldCreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    fldUpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
	fldFirstName VARCHAR(50) NOT NULL,
	fldLastName  VARCHAR(50) NOT NULL,
	fldEmail     VARCHAR(50) NOT NULL UNIQUE,
	fldPassword  VARCHAR(255) NOT NULL
);